learning_log/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.conf.urls import url

from rest_framework import routers
from learning_logs import views



from django.views.generic import TemplateView
router = routers.DefaultRouter() #路由
router.register(r'article', views.ArticleViewSet) #路由地址与接口配置


router.register(r'artcontent', views.ArtContentViewSet)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('learning_logs.urls')),
    path('users/', include('users.urls')),
    
    

    #vue.js测试页面
    # path('', TemplateView.as_view(template_name="index.html")),

    # re_path(r'^api/', include(router.urls)), #包含进路由配置的url
    # re_path(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
        #浏览器测试接口配置
    # re_path(r'^tinymce/', include('tinymce.urls')), 
]

learning_logs/urls.py
"""learning_logs URL Configuration
"""
# router.register(r'article', views.ArticleViewSet) #路由地址与接口配置
from django.urls import path, include,re_path
from . import views


app_name='learning_logs'
urlpatterns = [    
    path('',views.index,name='index'),
    re_path(r'^article/(?P<article_id>\d+)/$', views.article,name='article'),
    re_path(r'^look_chapter/(\d+)/(\w+)/$', views.look_chapter,name='look_chapter'),
    re_path(r'^new_chapter/(?P<article_id>\d+)/$', views.new_chapter,name='new_chapter'),
    # re_path(r'^edit_chapter/(?P<article_id>\d+)(?P<chapter_id>\d+)/$', views.edit_chapter,name='edit_chapter'),
    re_path(r'^edit_chapter/(\d+)/(\w+)/$',views.edit_chapter,name='edit_chapter'),
    re_path(r'^edit_art_content/(?P<article_id>\d+)/$', views.edit_art_content,name='edit_art_content'),
    re_path(r'^new_article/$', views.new_article, name='new_article'), 
    re_path(r'^search/$',views.search,name='search')
    ]


users/urls.py
"""users URL Configuration
"""
from django.urls import path, include,re_path
from . import views
#from django.contrib.auth.views import login（django1的版本）
from django.contrib.auth.views import LoginView#（django2的版本导入类）

LoginView.template_name = 'users/login.html'
app_name='users'
urlpatterns = [    
	#登录
    path('login/', LoginView.as_view(),
    	name='login'),    
    #注销
    re_path(r'^logout/$', views.logout_view, name='logout'),
    re_path(r'^register/$', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

from tinymce.models import HTMLField
#一对多
#User（系统自带）--Article（表1）
#Article（表1）--ArtContent（表2）
#Article（表1）--ArtLabel（表3）
#Article（表1）--ArtDiscuss（表5）
#User（系统自带）--ArtDiscuss（表5）
#一对一
#Article（表1）--ArtHot（表4）??
class Article(models.Model):
	"""文章表（表1）"""
	art_name=models.CharField('标题',max_length=200)
	art_add_date=models.DateTimeField(auto_now_add=True)
	art_author=models.CharField('作者',max_length=10,default="")
	user_owner=models.ForeignKey(User,on_delete=models.CASCADE)
	art_type=models.CharField('类型',max_length=200)
	art_status=models.CharField('状态',max_length=200,default="")
	art_introduction=models.CharField('简介',max_length=200,default="")
	art_name_used=models.CharField('曾用名',max_length=200,default="")
		
	def __str__(self):
		if len(self.art_name)>=20:
			art_name_limit=self.art_name[:20]+'...'
		else:
			art_name_limit=self.art_name
			#限制返回文章名字符数
		return art_name_limit 

class ArtContent(models.Model):
	"""文章章节内容表(表2）"""	
	chapter_name=models.CharField('章名',max_length=200)
	chapter_content=HTMLField('文章内容')
	article=models.ForeignKey(Article,verbose_name="文章",on_delete=models.CASCADE,null=True)
	chapter_add_date=models.DateTimeField(auto_now_add=True)
	class Meta:
		ordering=['chapter_add_date']

	
class ArtLabel(models.Model):
	"""标签内容表（表3）"""
	label_content=models.CharField('标签',max_length=20)
	article=models.ForeignKey(Article,on_delete=models.CASCADE)

class ArtHot(models.Model):
	"""文章热度表（表4）"""
	hot_evaluate=models.BigIntegerField('评价值',null=True,blank=True)
	hot_browse=models.BigIntegerField('浏览量',null=True,blank=True)
	hot_relay=models.BigIntegerField('转发数',null=True,blank=True)
	hot_share=models.BigIntegerField('分享数',null=True,blank=True)
	hot_discuss=models.BigIntegerField('讨论值',null=True,blank=True)
	article=models.OneToOneField(Article,on_delete=models.CASCADE)

class ArtDiscuss(models.Model):
	"""文章讨论表（表5)"""
	discuss_content=models.TextField('留言内容')
	discuss_add_date=models.DateTimeField(auto_now_add=True)
	discuss_owner=models.ForeignKey(User,on_delete=models.CASCADE)
	article=models.ForeignKey(Article,on_delete=models.CASCADE)
	



	




learning_logs/forms.py
from django import forms
from .models import Article,ArtContent

from django.forms import ModelForm

class ArticleForm(forms.ModelForm):
	#帖子表
	class Meta:
		model = Article
		# fields = ['invitation_text','invitation_title','invitation_label',
		# 	'invitation_energy','invitation_owner']
		fields = ['art_name','art_author','art_type',
			'art_status','art_introduction']
		labels = {'text': ''}
		widgets = {'text': forms.Textarea(attrs={'cols': 80})}

class ArtContentForm(forms.ModelForm):
	class Meta:
		model=ArtContent
		fields=['chapter_name','chapter_content']
		labels = {'text': ''}
		widgets = {'text': forms.Textarea(attrs={'cols': 80})}
		
	def __new__(cls, *args, **kwargs):
		#fields循环打印出组件
		#django是通过“__new__”方法，找到ModelForm里面的每个字段的，然后循环出每个字段添加自定义样式
		#cls.base_fields是一个元祖，里面是 所有的  【(字段名，字段的对象),(),()】
		for field_name in cls.base_fields:
			filed_obj = cls.base_fields[field_name]
			#添加属性
			filed_obj.widget.attrs.update({'class':'form-control'})

		return ModelForm.__new__(cls)

learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from . models import Article,ArtContent,ArtLabel,ArtHot,ArtDiscuss
from . forms import ArticleForm,ArtContentForm

from rest_framework import viewsets
from learning_logs.serializers import ArticleSerializers,ArtContentSerializers
from django.core.paginator import Paginator

def index(request):
	"""主页（文章列表页）"""
	articles=Article.objects.order_by('art_add_date')

	pre_four_articles=articles[0:4]
	print(pre_four_articles)
	surplus_articles=articles[4:]
	print(surplus_articles)
	print(bool(surplus_articles))
	context={'articles':articles,'pre_four_articles':pre_four_articles,'surplus_articles':surplus_articles}
	return render(request,'learning_logs/index.html',context)
	# return render(request,'article/list.html',context)

def article(request,article_id):
	"""文章详情页，具体单页"""
	article=Article.objects.get(id=article_id)
	artcontents=article.artcontent_set.all()
	#分页功能
	#20条一页
	# if len(artcontents)<=20:
	# 	num=len(artcontents)
	# else:
	# 	num=20
	paginator=Paginator(artcontents,10)
	current_page=int(request.GET.get('page',1))
	#分页标签显示7个
	if paginator.num_pages >7 :
		if current_page-3 < 1:
			page_ran=range(1,8)
		elif current_page +3 >paginator.num_pages:
			page_ran=range(paginator.num_pages-6,paginator.num_pages+1)
		else:
			page_ran=range(current_page-3,current_page+4)
		page_range=page_ran
	else:
		page_range=paginator.page_range


	current_page_content=paginator.page(current_page)
	context = {'article':article,'current_page_content':current_page_content,'page_range':page_range}
	return render(request,'learning_logs/article.html',context)

@login_required
def new_article(request):
	"""添加新文章"""
	if request.method != 'POST':
		form = ArticleForm()
	else:
		form = ArticleForm(request.POST)
		if form.is_valid():
			new_article = form.save(commit=False)
			new_article.user_owner=request.user
			new_article.save()
			return HttpResponseRedirect(reverse('learning_logs:index'))
	context ={'form':form}
	return render(request,'learning_logs/new_article.html',context)

@login_required
def edit_art_content(request,article_id):
	"""修改文章标题等内容"""
	article = Article.objects.get(id=article_id)
	art_content =article.artcontent_set.all()
	if article.user_owner != request.user:
		raise Http404
	if request.method != "POST":
		form = ArticleForm(instance=article)
	else:
		form = ArticleForm(instance=article,data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('learning_logs:article',
				args=[article.id]))
	context={'article':article,'art_content':art_content,'form':form}
	return render(request,'learning_logs/edit_art_content.html',context)

@login_required
def new_chapter(request,article_id):
	article = Article.objects.get(id=article_id)
	art_content=article.artcontent_set.all()
	if article.user_owner != request.user:
		raise Http404	
	if request.method !='POST':
		form=ArtContentForm()		
	else:
		#post的表单中外键article字段为null	
		form=ArtContentForm(request.POST)

		if form.is_valid:
			#验证成功后需要为外键article字段，设置参数（instance.article）为实例（article）
			form.instance.article=article
			#接受了POST以及article实例后保存
			form.save()
			return HttpResponseRedirect(reverse('learning_logs:article',args=[article_id]))
		else:
			raise Http404
	context={'form':form,'article':article}
	return render(request,'learning_logs/new_chapter.html',context)

from django.db.models.aggregates import Count
def look_chapter(request,art_id,chap_id):
	"""查看具体章节"""
	artcontent=ArtContent.objects.get(article_id=art_id,id=chap_id)
	article=Article.objects.get(id=art_id)
	# 上一章下一章
	previous= ArtContent.objects.filter(id__lt=chap_id, article_id=art_id).order_by('-id').first()
	next = ArtContent.objects.filter(id__gt=chap_id, article_id=art_id).order_by('id').first()
	context = {'artcontent': artcontent, 'article': article, 'previous': previous,'next':next}
	return render(request, 'learning_logs/look_chapter.html', context)


@login_required
def edit_chapter(request,article_id,chapter_id):
	#实例化具体一片文章
	article=Article.objects.get(id=article_id)
	#实例化具体的一章内容
	artcontent=ArtContent.objects.get(id=chapter_id)
	# """修改章节内容"""
	if article.user_owner!=request.user:
		raise Http404
	if request.method != 'POST':
		form=ArtContentForm(instance=artcontent)
	else:
		form=ArtContentForm(instance=artcontent,data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('learning_logs:look_chapter',
				args=[article.id,artcontent.id]))
	context ={'artcontent':artcontent,'form':form,'article':article}
	
	
	return render(request,'learning_logs/edit_chapter.html',context)
	

def search(request):
	"""搜索功能"""
	search_name=request.GET.get('search_name')
	error_msg=''

	if not search_name:
		error_msg='请输入关键词'

		return render(request,'learning_logs/index.html',{'error_msg': error_msg})
	articles=Article.objects.filter(art_name__icontains=search_name)
	return render(request,'learning_logs/search_results.html',
		{'error_msg': error_msg,'articles': articles})

class ArticleViewSet(viewsets.ModelViewSet):
    queryset = Article.objects.all() #集合
    serializer_class = ArticleSerializers  #序列化
class ArtContentViewSet(viewsets.ModelViewSet):
	queryset=ArtContent.objects.all()
	serializer_class=ArtContentSerializers

learning_logs/templates/learning_logs/article.html
{% extends 'learning_logs/base.html' %}

{% block header %}
<div class="container">
<div class="page-header">
<h2 class="text-center">{{ article }}</h2>
<p class="text-center">
	{% if article.user_owner == request.user %}
	<a href="{% url 'learning_logs:edit_art_content' article.id  %}">修改</a>
    <a href="{% url 'learning_logs:new_chapter' article.id%}">更新</a>
	{% endif %}

</p>
</div>
</div>
{% endblock header %}

{% block content %}

<div class="container">
    <div class="panel panel-default">

        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                {% if current_page_content.has_previous %}
                <li class="page-item"><a class="page-link" href="?current_page_content.previous_page_number" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                {% else %}
                <li class="disabled"><a class="page-link" href="" aria-label="Next"><span aria-hidden="true">&laquo;</span></a></li>
                {% endif %}

                {% for page in page_range %}
                <li class="page-item"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
                {% endfor %}

                {% if current_page_content.has_next%}
                <li><a class="page-link" href="?page={{current_page_content.next_page_number}}" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>
                {% else %}
                <li class="disabled"><a class="page-link"  href="" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>
                {% endif %}
            </ul>
        </nav>
        <div>
        章列表：
        </div>
        {% if current_page_content %}


        {% for i in current_page_content %}
        <div class="over_window" >
            <a href="{% url 'learning_logs:look_chapter' article.id i.id %}">{{i.chapter_name}}</a>
            <p>
            <small> 更新：{{i.chapter_add_date|date:'y m d H:i'}}</small>
            {% if article.user_owner == request.user %}
                <small><a href="{% url 'learning_logs:edit_chapter' article.id i.id%}">修改</a></small>
            {% endif %}
            </p>
        </div>
        {% endfor %}
    {% else %}
            <p><h4>暂无内容</h4></p>
    {% endif %}
    </div>
</div>
<style>
.over_window{
    white-space :nowrap;
    width: 99%;
    text-overflow: ellipsis;
    overflow: hidden;
}

</style>
{% endblock content %}

learning_logs/templates/learning_logs/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
	<head>
		<meta charset="utf-8">
	    <title>哦啦-_-创造</title>
        <meta name="keywords" content="小说,小说网,名著,古典小说,古典文学">
        <meta name="description" content="小说阅读,古典小说，推荐小说，阅读名著">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" />
		<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">

	</head>

	<body>
		<!-- 引入导航栏 -->
	    {% include 'header.html' %}

        {% block header %}{% endblock header %}
        <!-- 预留具体页面的位置 -->
        {% block content %}{% endblock content %}
		<!-- 引入注脚 -->
    	{% include 'footer.html' %}    	
    	<!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->
	    <script src="{% static 'jquery/jquery-3.3.1.js' %}"></script>
	    <script src="{% static 'popper/popper-1.14.4.js' %}"></script>    
	    <!-- 引入bootstrap的js文件 -->
	    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
	     <script src="/static/tiny_mce/tiny_mce.js"></script>
		<script>
		    tinyMCE.init({
		        'mode':'textareas',
		        'language':"zh",
		        // 'theme':'advanced',
		        'width':this.width,
		        'height':700,
		    })
		</script>
		<style type="text/css">
			
		</style>
	</body>
</html>

learning_logs/templates/learning_logs/edit_art_content.html
{% extends "learning_logs/base.html" %}

{% block header %}


{% endblock header %}


{% block content %}
<form class="form " style="width: 96%;margin: 2%" action="{% url 'learning_logs:edit_art_content' article.id %}" method='post'>
	<p>
		<a href="{% url 'learning_logs:article' article.id %}">返回《{{ article }}》章列表</a>
	</p>
    <p>修改作品信息：</p>
    {% csrf_token %}
	{% for item in form %}
            <div class="form-group" >

            <input class="form-control" placeholder="{{item.label}}" aria-describedby="error_msg" id="{{item.id_for_label}}" name="{{item.html_name}}" type="{{item.field.widget.input_type}}" />

            {% for error in item.errors %}
                <small id="error_msg" class="form-text text-muted">{{error}}</small>
            {% endfor%}

            </div>
    {% endfor %}
<button class="btn btn-primary col-md-12" name="submit">保存</button>
</form>
{% endblock content %}

learning_logs/templates/learning_logs/edit_chapter.html
{% extends 'learning_logs/base.html' %}

{% block header %}
<!-- <h6>{{ artcontent.chapter_name }}</h6> -->

{% endblock header %}

{% block content %}	
	<form action="{% url 'learning_logs:edit_chapter' article.id artcontent.id%}" method='post' class="form"  style="width: 96%;margin-left: 2%">
		{% csrf_token %}
		<table class="table table-striped">
        <h6 style="text-align: center">作品名称：{{article}}</h6>
         章名：   <button name="submit" class="btn btn-primary" style="float: right">保存本章</button>
		{{form.chapter_name}}
		章内容：{{form.chapter_content}}

		</table>


	</form>
	<style type="text/css">
		.form{
			padding-bottom:1%;
			
		}
	</style>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
<!-- extends表明此页面继承自 base.html 文件 -->
{% block header %}
<!-- <div class="container">
<h5>作品列表</h5>
</div> -->
{% endblock header %}

{% block content %}	

    <div class="recom_article">推荐：</div>
    <div >
    {%  for pre_four_article in pre_four_articles %}

    <div class="two_row">
        <div class="name_author_intr line_num">名称：<a href="{% url 'learning_logs:article' pre_four_article.id %}">{{ pre_four_article.art_name }}</a></div>
        <div class="name_author_intr line_num">作者：{{ pre_four_article.art_author }}</div>
        <div class="name_author_intr intr">简介：{{ pre_four_article.art_introduction }}</div>
    </div>

    {% endfor %}
    </div>
    <div class="recom_article">文章：</div>
    <div>
    {% if surplus_articles %}
    {%  for surplus_article in surplus_articles %}
        <div class="row_list">
            <div class="row_list_half">名称：<a href="{% url 'learning_logs:article' surplus_article.id %}">{{ surplus_article.art_name }}</a></div>
            <div class="row_list_half">作者：{{ surplus_article.art_author }}</div>

{#            <div style='clear: both'></div>#}

        </div>
    {% endfor %}
    {% else %}
        <div class="row_list">
        没有内容
        </div>
    {% endif %}
    </div>
    <div class="create_publish">
        <a href="{% url 'learning_logs:new_article' %}">创作发布</a>
    </div>


<div class="py-3 fixed-bottom bg2-white">
    <div class="container">
        <p class="m-0 text-center text-dark">联系方式：359975715@qq.com
        </p>
    </div>
</div>
<style type="text/css">
body{
    background-color:#f9f9f9;
}
.bg2-white{background-color: rgba(255,255,255,0.1);}
.name_author_intr{
    display: -webkit-box;
    -webkit-box-orient: vertical;
    -webkit-line-clamp: 2;
    overflow: hidden;
}
.line_num{
    -webkit-line-clamp: 1;
    width: 80%;
    padding: 1vmax 0 0 1vmax;
}
.intr{
    padding: 1vmax 0 0 1vmax;
}
.two_row{
    width: 48%;
    {#height: 23vmax;#}
    margin: 1vw 0 0 1%;
    display: inline-block;
    vertical-align:top;
    background-color: white;
    border-radius: 1vmax;
}
.row_list{
    width: 98%;
    margin: 1vw 0 0 2%;
    border-radius: 1vmax;
    overflow: hidden;
}
.row_list_half{
    width:50%;
    float: left;
    display: -webkit-box;
    -webkit-box-orient: vertical;
    -webkit-line-clamp: 1;
    overflow: hidden;
}
.create_publish{
    text-align: center;
    margin-top: 2vmax;
    font-size:x-large;
}
.recom_article{
    margin: 1vw 0 0 1%;
}
</style>

{% endblock content %}

learning_logs/templates/learning_logs/look_chapter.html
{% extends 'learning_logs/base.html' %}

{% block header %}

{% endblock header %}
{% block content %}

<div class="container">
    <p>
    <h3 class="text-center">{{ artcontent.chapter_name }}</h3>
    {% if article.user_owner == request.user%}
        <a href="{% url 'learning_logs:edit_chapter' article.id artcontent.id %}">修改</a>
    {% endif %}
    </p>

    <span>
    {% autoescape off %}
    {{artcontent.chapter_content}}
    {% endautoescape %}
    </span>


{% if previous and next %}
    <a href="{% url 'learning_logs:look_chapter' article.id previous.id %}">上一章</a>
    <a href="{% url 'learning_logs:look_chapter' article.id next.id %}">下一章</a>
{% elif not previous and not next%}
    <a href="{% url 'learning_logs:article' article.id %}">返回列表</a>
{% elif previous and not next%}
    <a href="{% url 'learning_logs:look_chapter' article.id previous.id %}">上一章</a>
    <a href="{% url 'learning_logs:article' article.id %}">返回列表</a>
{% elif not previous and next %}
    <a href="{% url 'learning_logs:article' article.id %}">返回列表</a>
    <a href="{% url 'learning_logs:look_chapter' article.id next.id %}">下一章</a>
{% endif %}


</div>
<style type="text/css">
span{font-size:19px}
	
</style>

	
{% endblock content %}

learning_logs/templates/learning_logs/new_article.html
{% extends "learning_logs/base.html" %}

{% block header %}
	<p class="text-center">输入作品相关信息</p>
{% endblock header %}

{% block content %}

<form action="{% url 'learning_logs:new_article' %}" method='post' class="form" style="width: 96%;margin: 2%">

        {% csrf_token %}
        {% for item in form %}
                <div class="form-group" >

                <input class="form-control" placeholder="{{item.label}}" aria-describedby="error_msg" id="{{item.id_for_label}}" name="{{item.html_name}}" type="{{item.field.widget.input_type}}" />

                {% for error in item.errors %}
                    <small id="error_msg" class="form-text text-muted">{{error}}</small>
                {% endfor%}

                </div>
        {% endfor %}
        <button name="submit" class="btn btn-primary col-md-12">发起</button>

</form>
{% endblock content %}

learning_logs/templates/learning_logs/new_chapter.html
{% extends "learning_logs/base.html" %}

{% block header %}

{% endblock header %}

{% block content %}

<form action="{% url 'learning_logs:new_chapter' article.id%}" method='post' class="form"  style="width: 96%;margin-left: 2%">

    <h6 style="text-align: center">作品名称：{{article}}</h6>
	{% csrf_token %}
	<table class="table">
     章名：   <button name="submit" class="btn btn-primary" style="float: right">保存本章</button>
	{{form.chapter_name}}章内容：{{form.chapter_content}}
	</table>


</form>

{% endblock content %}

learning_logs/templates/learning_logs/search_results.html
{% extends "learning_logs/base.html" %}
{% block header %}
	<h1>作品列表</h1>
{% endblock header %}
{% block content %}
	{% if error_msg %}
	    <p>{{ error_msg }}</p>
	{% endif %}

	{% for article in articles %}
	  <div>
	    <a href="{% url 'learning_logs:article' article.id %}">{{ article }}</a>
	  </div>
	{% empty %}
	  <div class="no-post">
	    没有搜索到符合条件的文章
	  </div>
	{% endfor %}
{% endblock content %}