learning_log/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.conf.urls import url

from rest_framework import routers
from learning_logs import views



from django.views.generic import TemplateView
router = routers.DefaultRouter() #路由
router.register(r'article', views.ArticleViewSet) #路由地址与接口配置


router.register(r'artcontent', views.ArtContentViewSet)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('learning_logs.urls')),
    path('users/', include('users.urls')),
    
    

    #vue.js测试页面
    # path('', TemplateView.as_view(template_name="index.html")),

    # re_path(r'^api/', include(router.urls)), #包含进路由配置的url
    # re_path(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
        #浏览器测试接口配置
    # re_path(r'^tinymce/', include('tinymce.urls')), 
]

learning_logs/urls.py
"""learning_logs URL Configuration
"""
# router.register(r'article', views.ArticleViewSet) #路由地址与接口配置
from django.urls import path, include,re_path
from . import views


app_name='learning_logs'
urlpatterns = [    
    path('',views.index,name='index'),
    re_path(r'^article/(?P<article_id>\d+)/$', views.article,name='article'),
    re_path(r'^look_chapter/(\d+)/(\w+)/$', views.look_chapter,name='look_chapter'),
    re_path(r'^new_chapter/(?P<article_id>\d+)/$', views.new_chapter,name='new_chapter'),
    # re_path(r'^edit_chapter/(?P<article_id>\d+)(?P<chapter_id>\d+)/$', views.edit_chapter,name='edit_chapter'),
    re_path(r'^edit_chapter/(\d+)/(\w+)/$',views.edit_chapter,name='edit_chapter'),
    re_path(r'^edit_art_content/(?P<article_id>\d+)/$', views.edit_art_content,name='edit_art_content'),
    re_path(r'^new_article/$', views.new_article, name='new_article'), 
    re_path(r'^search/$',views.search,name='search')
    ]


users/urls.py
"""users URL Configuration
"""
from django.urls import path, include,re_path
from . import views
#from django.contrib.auth.views import login（django1的版本）
from django.contrib.auth.views import LoginView#（django2的版本导入类）

LoginView.template_name = 'users/login.html'
app_name='users'
urlpatterns = [    
	#登录
    path('login/', LoginView.as_view(),
    	name='login'),    
    #注销
    re_path(r'^logout/$', views.logout_view, name='logout'),
    re_path(r'^register/$', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

from tinymce.models import HTMLField
#一对多
#User（系统自带）--Article（表1）
#Article（表1）--ArtContent（表2）
#Article（表1）--ArtLabel（表3）
#Article（表1）--ArtDiscuss（表5）
#User（系统自带）--ArtDiscuss（表5）
#一对一
#Article（表1）--ArtHot（表4）??
class Article(models.Model):
	"""文章表（表1）"""
	art_name=models.CharField('标题',max_length=200)
	art_add_date=models.DateTimeField(auto_now_add=True)
	art_author=models.CharField('作者',max_length=10,default="")
	user_owner=models.ForeignKey(User,on_delete=models.CASCADE)
	art_type=models.CharField('类型',max_length=200)
	art_status=models.CharField('状态',max_length=200,default="")
	art_introduction=models.CharField('简介',max_length=200,default="")
	art_name_used=models.CharField('曾用名',max_length=200,default="")
		
	def __str__(self):
		if len(self.art_name)>=20:
			art_name_limit=self.art_name[:20]+'...'
		else:
			art_name_limit=self.art_name
			#限制返回文章名字符数
		return art_name_limit 

class ArtContent(models.Model):
	"""文章章节内容表(表2）"""	
	chapter_name=models.CharField('章名',max_length=200)
	chapter_content=HTMLField('文章内容')
	article=models.ForeignKey(Article,verbose_name="文章",on_delete=models.CASCADE,null=True)
	chapter_add_date=models.DateTimeField(auto_now_add=True)
	class Meta:
		ordering=['chapter_add_date']

	
class ArtLabel(models.Model):
	"""标签内容表（表3）"""
	label_content=models.CharField('标签',max_length=20)
	article=models.ForeignKey(Article,on_delete=models.CASCADE)

class ArtHot(models.Model):
	"""文章热度表（表4）"""
	hot_evaluate=models.BigIntegerField('评价值',null=True,blank=True)
	hot_browse=models.BigIntegerField('浏览量',null=True,blank=True)
	hot_relay=models.BigIntegerField('转发数',null=True,blank=True)
	hot_share=models.BigIntegerField('分享数',null=True,blank=True)
	hot_discuss=models.BigIntegerField('讨论值',null=True,blank=True)
	article=models.OneToOneField(Article,on_delete=models.CASCADE)

class ArtDiscuss(models.Model):
	"""文章讨论表（表5)"""
	discuss_content=models.TextField('留言内容')
	discuss_add_date=models.DateTimeField(auto_now_add=True)
	discuss_owner=models.ForeignKey(User,on_delete=models.CASCADE)
	article=models.ForeignKey(Article,on_delete=models.CASCADE)
	



	




learning_logs/forms.py
from django import forms
from .models import Article,ArtContent

from django.forms import ModelForm

class ArticleForm(forms.ModelForm):
	#帖子表
	class Meta:
		model = Article
		# fields = ['invitation_text','invitation_title','invitation_label',
		# 	'invitation_energy','invitation_owner']
		fields = ['art_name','art_author','art_type',
			'art_status','art_introduction']
		labels = {'text': ''}
		widgets = {'text': forms.Textarea(attrs={'cols': 80})}

class ArtContentForm(forms.ModelForm):
	class Meta:
		model=ArtContent
		fields=['chapter_name','chapter_content']
		labels = {'text': ''}
		widgets = {'text': forms.Textarea(attrs={'cols': 80})}
		
	def __new__(cls, *args, **kwargs):
		#fields循环打印出组件
		#django是通过“__new__”方法，找到ModelForm里面的每个字段的，然后循环出每个字段添加自定义样式
		#cls.base_fields是一个元祖，里面是 所有的  【(字段名，字段的对象),(),()】
		for field_name in cls.base_fields:
			filed_obj = cls.base_fields[field_name]
			#添加属性
			filed_obj.widget.attrs.update({'class':'form-control'})

		return ModelForm.__new__(cls)

learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from . models import Article,ArtContent,ArtLabel,ArtHot,ArtDiscuss
from . forms import ArticleForm,ArtContentForm

from rest_framework import viewsets
from learning_logs.serializers import ArticleSerializers,ArtContentSerializers
from django.core.paginator import Paginator

def index(request):
	"""主页（文章列表页）"""
	articles=Article.objects.order_by('art_add_date')

	pre_four_articles=articles[0:4]
	print(pre_four_articles)
	surplus_articles=articles[4:]
	print(surplus_articles)
	print(bool(surplus_articles))
	context={'articles':articles,'pre_four_articles':pre_four_articles,'surplus_articles':surplus_articles}
	return render(request,'learning_logs/index.html',context)
	# return render(request,'article/list.html',context)

def article(request,article_id):
	"""文章详情页，具体单页"""
	article=Article.objects.get(id=article_id)
	artcontents=article.artcontent_set.all()
	#分页功能
	#20条一页
	# if len(artcontents)<=20:
	# 	num=len(artcontents)
	# else:
	# 	num=20
	paginator=Paginator(artcontents,10)
	current_page=int(request.GET.get('page',1))
	#分页标签显示7个
	if paginator.num_pages >7 :
		if current_page-3 < 1:
			page_ran=range(1,8)
		elif current_page +3 >paginator.num_pages:
			page_ran=range(paginator.num_pages-6,paginator.num_pages+1)
		else:
			page_ran=range(current_page-3,current_page+4)
		page_range=page_ran
	else:
		page_range=paginator.page_range


	current_page_content=paginator.page(current_page)
	context = {'article':article,'current_page_content':current_page_content,'page_range':page_range}
	return render(request,'learning_logs/article.html',context)

@login_required
def new_article(request):
	"""添加新文章"""
	if request.method != 'POST':
		form = ArticleForm()
	else:
		form = ArticleForm(request.POST)
		if form.is_valid():
			new_article = form.save(commit=False)
			new_article.user_owner=request.user
			new_article.save()
			return HttpResponseRedirect(reverse('learning_logs:index'))
	context ={'form':form}
	return render(request,'learning_logs/new_article.html',context)

@login_required
def edit_art_content(request,article_id):
	"""修改文章标题等内容"""
	article = Article.objects.get(id=article_id)
	art_content =article.artcontent_set.all()
	if article.user_owner != request.user:
		raise Http404
	if request.method != "POST":
		form = ArticleForm(instance=article)
	else:
		form = ArticleForm(instance=article,data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('learning_logs:article',
				args=[article.id]))
	context={'article':article,'art_content':art_content,'form':form}
	return render(request,'learning_logs/edit_art_content.html',context)

@login_required
def new_chapter(request,article_id):
	article = Article.objects.get(id=article_id)
	art_content=article.artcontent_set.all()
	if article.user_owner != request.user:
		raise Http404	
	if request.method !='POST':
		form=ArtContentForm()		
	else:
		#post的表单中外键article字段为null	
		form=ArtContentForm(request.POST)

		if form.is_valid:
			#验证成功后需要为外键article字段，设置参数（instance.article）为实例（article）
			form.instance.article=article
			#接受了POST以及article实例后保存
			form.save()
			return HttpResponseRedirect(reverse('learning_logs:article',args=[article_id]))
		else:
			raise Http404
	context={'form':form,'article':article}
	return render(request,'learning_logs/new_chapter.html',context)

from django.db.models.aggregates import Count
def look_chapter(request,art_id,chap_id):
	"""查看具体章节"""
	artcontent=ArtContent.objects.get(article_id=art_id,id=chap_id)
	article=Article.objects.get(id=art_id)
	# 上一章下一章
	previous= ArtContent.objects.filter(id__lt=chap_id, article_id=art_id).order_by('-id').first()
	next = ArtContent.objects.filter(id__gt=chap_id, article_id=art_id).order_by('id').first()
	context = {'artcontent': artcontent, 'article': article, 'previous': previous,'next':next}
	return render(request, 'learning_logs/look_chapter.html', context)


@login_required
def edit_chapter(request,article_id,chapter_id):
	#实例化具体一片文章
	article=Article.objects.get(id=article_id)
	#实例化具体的一章内容
	artcontent=ArtContent.objects.get(id=chapter_id)
	# """修改章节内容"""
	if article.user_owner!=request.user:
		raise Http404
	if request.method != 'POST':
		form=ArtContentForm(instance=artcontent)
	else:
		form=ArtContentForm(instance=artcontent,data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('learning_logs:look_chapter',
				args=[article.id,artcontent.id]))
	context ={'artcontent':artcontent,'form':form,'article':article}
	
	
	return render(request,'learning_logs/edit_chapter.html',context)
	

def search(request):
	"""搜索功能"""
	search_name=request.GET.get('search_name')
	error_msg=''

	if not search_name:
		error_msg='请输入关键词'

		return render(request,'learning_logs/index.html',{'error_msg': error_msg})
	articles=Article.objects.filter(art_name__icontains=search_name)
	return render(request,'learning_logs/search_results.html',
		{'error_msg': error_msg,'articles': articles})

class ArticleViewSet(viewsets.ModelViewSet):
    queryset = Article.objects.all() #集合
    serializer_class = ArticleSerializers  #序列化
class ArtContentViewSet(viewsets.ModelViewSet):
	queryset=ArtContent.objects.all()
	serializer_class=ArtContentSerializers

learning_logs/templates/footer.html
{% load staticfiles %}
<!-- Footer -->
<div>
    <br><br><br>
</div>
<footer class="py-3 fixed-bottom bg2-white">
{#    <div class="container">#}
{#        <p class="m-0 text-center text-dark">联系方式：359975715@qq.com#}
{#        <script type="text/javascript">#}
{#        if#}
{#            (localStorage.pagecount)#}
{#            {localStorage.pagecount=Number(localStorage.pagecount) +1;}#}
{#        else#}
{#            {localStorage.pagecount=1;}#}
{#            document.write("访问数: " + localStorage.pagecount );#}
{#        </script>#}
{#        </p>#}
{#    </div>#}
{#    <style type="text/css">#}
{#        .bg2-white{background-color: rgba(255,255,255,0.1);}        #}
{#    </style>#}
</footer>

learning_logs/templates/header.html
<!-- 定义导航栏 -->
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light ">
    
    <a class="navbar-brand" href="{% url 'learning_logs:index' %}">书籍</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">

        <!-- <li class="nav-item active">
          <a class="nav-link" href="{% url 'learning_logs:index' %}">视创<span class="sr-only">(current)</span></a>
        </li> -->
        <!-- <li class="nav-item">
          <a class="nav-link" href="{% url 'learning_logs:index' %}">音创</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            游创
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">反馈</a>
        </li> -->
      </ul>
      <ul class="navbar-nav mr-auto">
        <form class="form-inline mr-auto my-2 my-lg-0" method="get" action="{% url 'learning_logs:search' %}">
          {% csrf_token %}
          <input class="form-control mr-sm-2" type="search" placeholder="搜索" aria-label="Search" name="search_name" required>
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
        </form>
      </ul>
      <ul class="navbar-nav mr-right">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" >您好, {{ user.username }}.</a>
          </li>    
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'users:logout' %}">退出</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'users:register' %}">注册</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'users:login' %}">登录</a>
          </li>
        {% endif %}
      </ul>     
    </div>
  </nav>
</div>